post_install() {
    if ! grep -q s6log /etc/passwd; then
        useradd -r s6log -s /usr/bin/nologin
        usermod -aG s6log root
        chgrp s6log /var/log
        chmod g+rwx /var/log
    fi
}

post_upgrade() {
    if ! grep -q s6log /etc/passwd; then
        useradd -r s6log -s /usr/bin/nologin
        usermod -aG s6log root
        chgrp s6log /var/log
        chmod g+rwx /var/log
    fi
}
