# Maintainer: Cory Sanin <corysanin@artixlinux.org>
# Note: This PKGBUILD is automatically generated by the scripts at https://cgit.kde.org/kdesdk-devenv-dependencies.git/
# Don't manually edit the PKGBUILD, edit the upstream template instead

pkgname=kde-development-environment-meta
pkgver=20240227
pkgrel=1
pkgdesc='Metapackage to install a full KDE development environment'
arch=(any)
url='https://phabricator.kde.org/T3722'
license=(LGPL)
makedepends=()
source=(org.kde.development.appdata.xml kdesdk-devenv-dependencies.svg)
sha256sums=('49a9f3a5d875162e50288c845b44592dc6eaa7471ff8512df2296525d218e301'
            '92af2376f53429735903ff6706344566c7f0f1aa6cfd5d2cf7aaad7097c71238')
noextract=()

package() {
    depends=(attica
         bash-completion
         bear
         cmake
         extra-cmake-modules
         gcc
         gettext
         git
         kactivities
         karchive
         kauth
         kbookmarks
         kcmutils
         kcodecs
         kcolorscheme
         kcompletion
         kconfig
         kconfigwidgets
         kcoreaddons
         kcrash
         kdbusaddons
         kdeclarative
         kdoctools
         kglobalaccel
         kguiaddons
         ki18n
         kiconthemes
         kio
         kirigami
         kitemviews
         kjobwidgets
         knotifications
         kpackage
         kparts
         kplotting
         kpty
         kservice
         ksvg
         ktextwidgets
         kunitconversion
         kwallet
         kwayland
         kwidgetsaddons
         kwindowsystem
         kxmlgui
         make
         ninja
         plasma-framework
         qt6-base
         qt6-declarative
         qt6-webengine
         solid
         sonnet
         threadweaver)
    optdepends=(kate
            kdevelop
            plasma-sdk
            plasma-workspace)

    install -Dm644 org.kde.development.appdata.xml "$pkgdir"/usr/share/metainfo/org.kde.development.appdata.xml
    install -Dm644 kdesdk-devenv-dependencies.svg "$pkgdir"/usr/share/icons/hicolor/scalable/apps/kdesdk-devenv-dependencies.svg
}
