pre_install() {
  pre_upgrade
}

pre_upgrade() {
    version=$(pacman -Qi s6-scripts | grep "^Version" | cut -f2 -d ":" | cut -f2 -d " ")
    cmp=$(vercmp "${version}" "20240416-2"
    if [ $cmp -eq -1 ]; then
        echo "tty1 -> tty1-srv" >> /etc/s6/config/convfile
        echo "tty2 -> tty2-srv" >> /etc/s6/config/convfile
        echo "tty3 -> tty3-srv" >> /etc/s6/config/convfile
        echo "tty4 -> tty4-srv" >> /etc/s6/config/convfile
        echo "tty5 -> tty5-srv" >> /etc/s6/config/convfile
        echo "tty6 -> tty6-srv" >> /etc/s6/config/convfile
        echo "ttyS -> ttyS-srv" >> /etc/s6/config/convfile
    fi
}
