#!/usr/bin/env bash

do_lock() {
	cryptsetup luksClose "$1" >/dev/null
}

read_crypttab() {
	local line nspo
	while read line <&3; do
		[[ $line && $line != '#'* ]] || continue
		eval nspo=("${line%#*}")
		do_lock "${nspo[0]}" "${nspo[1]}" "${nspo[2]}" "${nspo[3]}"
	done 3< /etc/crypttab
}

vgchange --sysinit -a n &>/dev/null
read_crypttab
