#!/usr/bin/execlineb -P
envfile /etc/s6/sv/backuppc-log/conf
importas -iu DIRECTIVES DIRECTIVES
foreground { if -n -t { test -d /var/log/backuppc } install -d -m 0755 -o s6log -g s6log /var/log/backuppc }
foreground { chmod -R 755 /var/log/backuppc }
foreground { touch /var/log/backuppc/LOG }
foreground { chown backuppc /var/log/backuppc/LOG }
s6-setuidgid s6log exec -c sh -c "s6-log -d3 -b ${DIRECTIVES} /var/log/backuppc"
