pre_upgrade() {
	echo "Warning: this update will restart your dbus service."
	echo "This may kill your graphical session. Save your work before proceeding."
	echo "Press 'ctrl+\' to quit the update. Press 'ctrl+c' to continue."
	echo "If you quit, you need to manually remove the /var/lib/pacman/db.lck file."
	while true; do
		sleep infinity
	done
}

pre_remove() {
    if [ -e "/run/service/dbus" ]; then
        s6-rc -d change dbus
    fi
}
