#!/bin/sh
if [ -e /etc/s6-linux-init ]; then
    if [ -e /etc/s6-linux-init/current ]; then
        rm -rf /etc/s6-linux-init/current
    fi
    s6-linux-init-maker -1 -G "/usr/bin/agetty -L -8 tty1 115200" /etc/s6-linux-init/current
    mv /etc/s6-linux-init/current/bin/init /etc/s6-linux-init/current/bin/s6-init
    rm /etc/s6-linux-init/current/scripts/*
    cp -r /etc/s6-linux-init/current/bin /usr
    ln -s /etc/s6-linux-init/skel/rc.init /etc/s6-linux-init/current/scripts/rc.init
    ln -s /etc/s6-linux-init/skel/rc.shutdown /etc/s6-linux-init/current/scripts/rc.shutdown
    ln -s /etc/s6-linux-init/skel/rc.shutdown.final /etc/s6-linux-init/current/scripts/rc.shutdown.final
    ln -s /etc/s6-linux-init/skel/runlevel /etc/s6-linux-init/current/scripts/runlevel
fi
