#!/bin/sh -e
timestamp=$(date +%s)
s6-rc-compile /etc/s6/rc/compiled-$timestamp /etc/s6/sv
if [ -e "/run/service" ]; then
    s6-rc-update /etc/s6/rc/compiled-$timestamp
fi
if [ -d "/etc/s6/rc/compiled" ]; then
	ln -sf /etc/s6/rc/compiled-$timestamp /etc/s6/rc/compiled/compiled && mv -f /etc/s6/rc/compiled/compiled /etc/s6/rc
else
	ln -sf /etc/s6/rc/compiled-$timestamp /etc/s6/rc/compiled
fi
len="$(find /etc/s6/rc -name "compiled*" -type d | wc -l)"
find /etc/s6/rc -name "compiled*" -type d | sort -n | head -n "$(($len-1))" | xargs rm -rf
echo "s6-rc database updated. Don't forget to redo your bundles."
