#!/bin/bash -e

args=()
all=0

build_presets() {
    local name="$1" ver="$2"
    local initramfs=/boot/initramfs-"${name}"-dracut.img
    local fallback=/boot/initramfs-"${name}"-dracut-fallback.img
    for preset in 'default' 'fallback';do
        case $preset in
            'default') args=(-fMqH "${initramfs}" "${ver}") ;;
            *) args=(-fMq "${fallback}" "${ver}") ;;
        esac
        if (( ${#args[@]} )); then
            echo "==> Building image: $preset"
            echo "  -> ${args[@]}"
            echo "==> Starting build: ${ver}"
            dracut "${args[@]}"
        fi
    done
}

while read -r line; do
    if [[ $line != */vmlinuz ]]; then
        # triggers when it's a change to usr/lib/dracut/modules.d/*
        all=1
        continue
    fi

    if ! read -r pkgbase > /dev/null 2>&1 < "${line%/vmlinuz}/pkgbase"; then
        # if the kernel has no pkgbase, we skip it
        continue
    fi

    kver=${line%*/vmlinuz}
    kver=${kver##*/}

    # always install the kernel
    install -Dm644 "${line}" "/boot/vmlinuz-${pkgbase}"
done

if (( all )); then
    # build for all kernels
    kernels=$(compgen -G /usr/lib/modules/"*")
    for kernel in ${kernels[@]}; do
        if ! read -r pkgbase > /dev/null 2>&1 < "${kernel}/pkgbase"; then
            # if the kernel has no pkgbase, we skip it
            continue
        fi

        build_presets "${pkgbase}" "${kernel##*/}"
    done
else
    # build for tigger
    build_presets "${pkgbase}" "${kver}"
fi
