#!/usr/bin/openrc-run
# Copyright (c) 2008 Saleem Abdulrasool <compnerd@compnerd.org>
# Copyright 2013-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

description="NetworkManager daemon. The service is marked as started only \
when a network connection is established."
supervisor="supervise-daemon"
command="/usr/bin/NetworkManager"
command_args="-n"
pidfile="/run/NetworkManager/NetworkManager.pid"

depend() {
    need dbus
    use logind
    provide net
}

start_pre() {
    checkpath -q -d -m 0755 /run/NetworkManager
}
