#!/usr/bin/openrc-run
# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

name="lighttpd"
description="Lighttpd web server"

conf_file="${LIGHTTPD_CONF:-/etc/lighttpd/lighttpd.conf}"
extra_started_commands="reload graceful"
required_files="${conf_file}"
pidfile="/run/${RC_SVCNAME}.pid"
command="/usr/bin/lighttpd"
command_args="-f ${conf_file}"
command_foreground_args="-D"

depend() {
	need net
	use mysql logger spawn-fcgi ldap slapd netmount dns
	after firewall
	after famd
	after sshd
}

checkconfig() {
	ebegin "Checking for ${conf_file}"
	if [ ! -f "${conf_file}" ] ; then
		eerror "${conf_file} does not exist."
	fi
	eend $?

	/usr/bin/lighttpd -t -f "${conf_file}" >/dev/null
}

start_pre() {
	checkconfig || return $?
	checkpath -d -q -m 0750 /run/lighttpd/
}

check_running() {
	if ! service_started "${SVCNAME}" ; then
		eerror "${SVCNAME} isn't running"
	fi
	checkconfig || return $?
}

reload() {
	check_running
	ebegin "Re-opening lighttpd log files"
	start-stop-daemon --quiet --pidfile "${LIGHTTPD_PID}" \
		--signal HUP
	eend $?
}

graceful() {
	check_running
	ebegin "Gracefully stopping lighttpd"
	start-stop-daemon --quiet --pidfile "${LIGHTTPD_PID}" \
		--signal INT
	if eend $? ; then
		rm -f "${LIGHTTPD_PID}"
		start
	fi
}
