#!/usr/bin/openrc-run

command="/usr/bin/wg-quick"
command_args="up ${WIREGUARD_INTERFACE}"
required_files="/etc/wireguard/${WIREGUARD_INTERFACE}.conf"
extra_commands="save add sync"
description_save="Save configuration"
description_add="Add interface without distrupting service"

depend() {
	need localmount
	use dns
	provide vpn ipsec
	keyword -shutdown
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	"${command}" down "${WIREGUARD_INTERFACE}"
	eend $?
}

save() {
	ebegin "Saving configuration"
	"${command}" save "${WIREGUARD_INTERFACE}"
	eend $?
}


add() {
	if [ ! -f "/etc/wireguard/${WIREGUARD_NFACE}.conf" ]; then
		eerror "Config for ${WIREGUARD_NFACE} not found"
	else
		ebegin "Adding interface ${WIREGUARD_NFACE}"
		wg addconf "${WIREGUARD_NFACE}" "/etc/wireguard/${WIREGUARD_NFACE}.conf"
		"${command}" strip "$WIREGUARD_NFACE"
		eend $?
	fi
}


sync() {
	if [ ! -f "/etc/wireguard/${WIREGUARD_INTERFACE}.conf" ]; then
		eerror "Config for ${WIREGUARD_INTERNFACE} not found"
	else
		ebegin "Syncing ${WIREGUARD_INTERFACE} configuration"
		wg syncconf "${WIREGUARD_INTERFACE}" "/etc/wireguard/${WIREGUARD_INTERFACE}.conf"
		eend $?
	fi
}
