#!/usr/bin/openrc-run
# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Purpose License v2

depend() {
   need dbus
   provide net
}

start() {
   ebegin "Starting Connection Manager"
   start-stop-daemon --start --quiet --exec /usr/bin/connmand -- ${CONNMAN_OPTS}
   eend $?
}

stop() {
   ebegin "Stopping Connection Manager"
   start-stop-daemon --stop --quiet --exec /usr/bin/connmand
   eend $?
}
