#!/usr/bin/openrc-run
# This file is part of Fail2Ban.
#
# Fail2Ban is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Fail2Ban is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fail2Ban; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Author: Sireyessire, Cyril Jaquier
#

description="Daemon to ban hosts that cause multiple authentication errors"
description_reload="reload configuration"
description_showlog="show fail2ban logs"

pidfile=/run/fail2ban/fail2ban.pid
command=/usr/bin/fail2ban-client
command_args="${FAIL2BAN_OPTIONS} start"
extra_started_commands="reload showlog"

depend() {
        need net
        need logger
        after iptables
}

start_pre() {
	checkpath -d /run/fail2ban || return $?
        
	# remove stalled sock file after system crash
        # bug 347477
        rm -f /run/fail2ban/fail2ban.sock || return $?
}

reload() {
        ebegin "Reloading fail2ban"
        "$command" reload
        eend $? "Failed to reload fail2ban"
}

showlog(){
        less /var/log/fail2ban.log
}
