#!/usr/bin/openrc-run

name="fcgiwrap"
description="fcgiwrap cgi daemon"

command="/usr/bin/fcgiwrap"
user="http"
group="http"
: ${socket:=unix:/run/fcgiwrap/fcgiwrap.sock}

depend() {
	need net localmount
	after firewall
}

start_pre() {
	command_args="-c ${nproc:-$(nproc)} -s $socket"
	case "$socket" in
	unix:/*)
		local socket_path=${socket#unix:}
		checkpath --directory --mode 2775 --owner http:http \
			${socket_path%/*}
		;;
	esac
}

start() {
	ebegin "Starting ${name}"
	start-stop-daemon --exec ${command} \
		--background \
		-u http -g http \
		--start -- ${command_args}
	eend $?
}

stop_post() {
	case "$socket" in
	unix:/*)
		rm -f "${socket#unix:}"
		;;
	esac
}
