pre_remove() {
  if [ -e /run/service/grafana-srv ]; then
    s6-rc -d change grafana
  fi
}

post_install() {
  if [ -f /etc/s6/sv/postgresql/run ]; then
    echo "postgresql" >> /etc/s6/sv/grafana-srv/dependencies
  fi

  if [ -f /etc/s6/sv/mysqld-srv/run ]; then
    echo "mysqld" >> /etc/s6/sv/grafana-srv/dependencies
  fi
}

post_ugprade() {
  post_install
}

pre_remove() {
  rm /etc/s6/sv/grafana-srv/dependencies
}
