#!/usr/bin/openrc-run

name=radicale
description="A simple CalDAV (calendar) and CardDAV (contact) server"

pidfile="/run/${RC_SVCNAME}.pid"
command=/usr/bin/radicale
command_user=radicale:radicale
command_background=true

depend() {
	use net
	need localmount
}

start_pre() {
	checkpath --directory --owner radicale /var/lib/radicale
	checkpath --directory --owner radicale /var/log/radicale
	checkpath --file --owner root:radicale --mode 0640 /etc/radicale/config
	checkpath --file --owner root:radicale --mode 0640 /etc/radicale/logging
}
