pre_remove() {
    if [ -e "/run/service/s6rc-oneshot-runner" ]; then
	s6-rc -d change cryptsetup
    fi
    sed -i '/cryptsetup/d' /etc/s6/sv/mount-init/dependencies
}

post_install() {
    if ! grep -q cryptsetup /etc/s6/sv/mount-init/dependencies; then
	echo "cryptsetup" >> /etc/s6/sv/mount-init/dependencies
    fi
    echo "  cryptsetup-s6 automatically installs itself into the boot bundle."
    echo "  There's no need to add it to the default bundle."
}

post_upgrade() {
    post_install
}
