pre_remove() {
    if [ -e "/run/service/dbus-srv" ]; then
        s6-rc -d change dbus
    fi
    sed -i '/dbus/d' /etc/s6/sv/misc/contents
}

post_install() {
    if ! grep -q dbus /etc/s6/sv/misc/contents; then
        echo "dbus" >> /etc/s6/sv/misc/contents
    fi
	echo "  dbus-s6 automatically installs itself into the boot bundle."
	echo "  There's no need to add it to the default bundle."
}

post_upgrade() {
    post_install
}

post_remove() {
    rm -rf /etc/s6/sv/dbus-log
}
