pre_remove() {
    if [ -e "/run/service/elogind-srv" ]; then
        s6-rc -d change elogind
    fi
    sed -i '/elogind/d' /etc/s6/sv/misc/contents
}

post_install() {
    if ! grep -q elogind /etc/s6/sv/misc/contents; then
        echo "elogind" >> /etc/s6/sv/misc/contents
    fi
	echo "  elogind-s6 automatically installs itself into the boot bundle."
	echo "  There's no need to add it to the default bundle."
}

post_upgrade() {
    post_install
}

post_remove() {
    rm -rf /etc/s6/sv/elogind-log
}
