pre_remove() {
    if [ -e "/run/service/elogind" ]; then
        s6-rc -d change elogind
    fi
}

post_upgrade() {
    echo "   There will be some command errors on this upgrade."
    echo "   It is normal. This is to make sure elogind doesn't restart."
    sh /usr/share/libalpm/scripts/s6-rc-db-update-hook
    contents=$(s6-rc-db -c /etc/s6/rc/compiled contents default)
    add_elogind=false
    for entry in $contents; do
        if [ "$entry" = "elogind-srv" ]; then
            s6-rc-bundle-update delete default elogind
            s6-rc-bundle-update delete default elogind-srv
            add_elogind=true
        fi;
        if [ "$entry" = "elogind-log" ]; then
            s6-rc-bundle-update delete default elogind-log
        fi
    done
    if [ $add_elogind = true ]; then
        s6-rc-bundle-update add default elogind
    fi
    echo "   Note: elogind-srv/elogind-srv are deprecated and will be removed in the future."
    echo "   Instead, use the new elogind service directly (this is now the default)."
}
