post_install() {
    cryptsetup=$(pacman -Qi cryptsetup-s6 2> /dev/null)
    if [[ "$?" == "0" ]]; then
        echo "cryptsetup" >> /etc/s6/sv/mount-filesystems/dependencies
    fi
    dbus=$(pacman -Qi dbus-s6 2> /dev/null)
    if [[ "$?" == "0" ]]; then
        echo "dbus" >> /etc/s6/sv/misc/contents
    fi
    elogind=$(pacman -Qi elogind-s6 2> /dev/null)
    if [[ "$?" == "0" ]]; then
        echo "elogind" >> /etc/s6/sv/misc/contents
    fi
    eudev=$(pacman -Qi eudev-s6 2> /dev/null)
    if [[ "$?" == "0" ]]; then
        echo "udev" >> /etc/s6/sv/boot/contents
        echo "udev" >> /etc/s6/sv/mount-filesystems/dependencies
        echo "udev" >> /etc/s6/sv/mount-net/dependencies
        echo "udev" >> /etc/s6/sv/random-seed/dependencies
    fi
    lvm2=$(pacman -Qi lvm2-s6 2> /dev/null)
    if [[ "$?" == "0" ]]; then
        echo "lvm2" >> /etc/s6/sv/mount-filesystems/dependencies
    fi
}

post_upgrade() {
    post_install
}

post_remove() {
    rm -rf /etc/s6/sv/mount-net/dependencies
    rm -rf /etc/s6/sv/rc-local/dependencies
}
