pre_remove() {
    if [ -e "/run/service/wpa_supplicant-srv" ]; then
        s6-rc -d change wpa_supplicant
    fi
    sed -i '/wpa_supplicant/d' /etc/s6/sv/mount-net/dependencies
}

post_remove() {
    rm -rf /etc/s6/sv/wpa_supplicant-log
    rm -rf /etc/s6/sv/wpa_supplicant-srv
}

post_install() {
    echo "  dhcpcd-s6 needs to be running for wpa_supplicant to actually get a network connection!"
}

post_upgrade() {
    post_install
}
