post_install() {
    cryptsetup=$(pacman -Qi cryptsetup-s6 2> /dev/null)
    if [[ "$?" == "0" ]]; then
        echo "cryptsetup" >> /etc/s6/sv/mount-filesystems/dependencies
    fi
    lvm2=$(pacman -Qi lvm2-s6 2> /dev/null)
    if [[ "$?" == "0" ]]; then
        echo "lvm2" >> /etc/s6/sv/mount-filesystems/dependencies
    fi
}

post_upgrade() {
    post_install
}

post_remove() {
    rm -rf /etc/s6/sv/dmesg
    rm -rf /etc/s6/sv/mount-net
    rm -rf /etc/s6/sv/rc-local
    rm -rf /etc/s6/sv/udevd-log
}
