post_install() {
    rm -rf /tmp/current
    mv /etc/s6/current /tmp
    s6-linux-init-maker -1 -f /etc/s6/skel -G "/usr/bin/agetty -L -8 tty1 115200" -c /etc/s6/current /etc/s6/current
    mv /etc/s6/current/bin/init /etc/s6/current/bin/s6-init
    rm -rf /etc/s6/current/scripts
    mv /tmp/current/scripts /etc/s6/current
    cp -a /etc/s6/current/bin /usr
}

post_upgrade() {
    rm -rf /tmp/current
    mv /etc/s6/current /tmp
    s6-linux-init-maker -1 -f /etc/s6/skel -G "/usr/bin/agetty -L -8 tty1 115200" -c /etc/s6/current /etc/s6/current
    mv /etc/s6/current/bin/init /etc/s6/current/bin/s6-init
    rm -rf /etc/s6/current/scripts
    mv /tmp/current/scripts /etc/s6/current
    cp -a /etc/s6/current/bin /usr
}
