#!/bin/sh
if [ -e /etc/s6-linux-init ]; then
    if [ -e /etc/s6-linux-init/current ]; then
        cp -r /etc/s6-linux-init/current/scripts/ /tmp
        echo "Old rc scripts moved to /tmp/scripts/*. Please back them up if they are important."
        rm -rf /etc/s6-linux-init/current
    fi
    s6-linux-init-maker -1 -G "/usr/bin/agetty -L -8 tty1 115200" /etc/s6-linux-init/current
    mv /etc/s6-linux-init/current/bin/init /etc/s6-linux-init/current/bin/s6-init
    if [ -e /usr/bin/halt ]; then mv /usr/bin/halt /tmp; fi
    if [ -e /usr/bin/poweroff ]; then mv /usr/bin/poweroff /tmp; fi
    if [ -e /usr/bin/reboot ]; then mv /usr/bin/reboot /tmp; fi
    if [ -e /usr/bin/s6-init ]; then mv /usr/bin/s6-init /tmp; fi
    if [ -e /usr/bin/shutdown ]; then mv /usr/bin/shutdown /tmp; fi
    if [ -e /usr/bin/telinit ]; then mv /usr/bin/telinit /tmp; fi
	cp -r /etc/s6-linux-init/current/bin /usr
    echo "Old init binaries moved to /tmp/*. Use those for rebooting."
fi
